### ISSUE TITLE
Can't signup with Rails validations

### ISSUE THREAD

**Issue by pluralism** [pluralism/ldso1516#3]
Hi guys!

I've noticed that the Rails app won't pass the validations with on: :update when we try to sign up. This happens because the record is immediately updated after being created. What do you suggest to do? I was thinking about adding a new field to the User model that would tell if the record was already updated or not. Then during the sign up we wouldn't run the validations.

**Comment by pluralism** [comment]
@Famarante, @momoepro, @zukuyama , @HugoFAC , @karamot Guys, this issue is now marked for review. Please do a git pull and test if the update action is now working.

**Comment by pluralism** [comment]
@Famarante , @momoepro , @zukuyama , @karamot , @HugoFAC Guys, this issue is now marked for review. Please do a git pull and test it so I can mark this as closed.

**Comment by zukuyama** [comment]
Passed on testes ya can close andre
